# Generated by Django 5.1.3 on 2025-06-17 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceChanger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_audio", models.FileField(upload_to="original_voices/")),
                (
                    "effect_applied",
                    models.CharField(
                        choices=[
                            ("robot", "Robot"),
                            ("chipmunk", "Chipmunk"),
                            ("echo", "Echo"),
                            ("deep", "Deep Voice"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "converted_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="voice_changer/converted/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("converted_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
